### ISSUE TITLE
Autogen issues under CentOS 6

### ISSUE THREAD

**Issue by CanadianJeff** [djcsdy/swfmill#45]
```
[root@jeff:/usr/src/swfmill] # ./autogen.sh
which: no glibtoolize in (/usr/local/jdk/bin:/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/opt/cpanel/composer/bin:/usr/local/rvm/bin:/usr/local/bin:/usr/X11R6/bin:/root/bin)
/usr/bin/m4:configure.ac:36: recursion limit of 1024 exceeded, use -L<N> to change it
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: autom4te failed with exit status: 1
```

**Comment by djcsdy** [comment]
I’ve never used CentOS so I’m not sure how to help here except to offer some general suggestions:

1. `glibtoolize` might be called `libtoolize` on CentOS. So try editing `autogen.sh` to change `glibtoolize` to `libtoolize` and see if that helps.
2. Make sure you have installed whatever package contains `libtoolize`/`glibtoolize`. On CentOS I think that package is `libtool`.

Hopefully the other errors will disappear once you make `glibtoolize`/`libtoolize` available.

Please let me know if you find/found a solution that works.
